model:
  embedding_dim: 768
  encoder_type: "resnet"
  encoder_kwargs:
    hidden_dim: 256
    n_layers: 2

training:
  learning_rate: 0.0005

data:
  batch_size: 32
  
logging:
  experiment_name: "baseline_DAVIS_cold"
  save_dir: "outputs/baseline/DAVIS/cold"

gridsearch: # 500s (10 mins) for a run, max 6 gb mem used on Davis -> 4 jobs, 24 hours each
  model.embedding_dim: [512, 768, 1024]
  model.encoder_type: ["resnet", "transformer"]
  model.encoder_kwargs.hidden_dim: [128, 256, 512]
  model.encoder_kwargs.n_layers: [2, 3, 4]

  training.learning_rate: [0.0005, 0.001, 0.002]
  data.batch_size: [16, 32, 64]