model:
  embedding_dim: 768
  hidden_dim: 128
  factor: 4
  n_layers: 3
  dropout: 0.2
  encoder_type: "resnet"

training:
  learning_rate: 0.0005

data:
  batch_size: 32
  
logging:
  save_dir: "data/results/baseline/DAVIS/cold"

gridsearch: # 500s (10 mins) for a run, max 6 gb mem used on Davis -> 4 jobs, 24 hours each (took only 9 hours; rand split much longer...)
  model.embedding_dim: [512, 768, 1024]
  model.encoder_type: ["resnet", "transformer"]
  model.hidden_dim: [128, 256, 512]
  model.n_layers: [2, 3, 4]

  training.learning_rate: [0.0005, 0.001, 0.002]
  data.batch_size: [16, 32, 64]

ensemble: # Top 5 performing configurations from gridsearch results (<1 hr)
  configs:
    - training.learning_rate: 0.0005
      data.batch_size: 32
      model.hidden_dim: 128
      model.n_layers: 3
      model.embedding_dim: 768
      model.encoder_type: "resnet"
    
    - training.learning_rate: 0.0010
      data.batch_size: 16
      model.hidden_dim: 128
      model.n_layers: 2
      model.embedding_dim: 512
      model.encoder_type: "resnet"
    
    - training.learning_rate: 0.0020
      data.batch_size: 16
      model.hidden_dim: 128
      model.n_layers: 3
      model.embedding_dim: 512
      model.encoder_type: "resnet"
    
    - training.learning_rate: 0.0005
      data.batch_size: 16
      model.hidden_dim: 128
      model.n_layers: 2
      model.embedding_dim: 512
      model.encoder_type: "resnet"
    
    - training.learning_rate: 0.0010
      data.batch_size: 32
      model.hidden_dim: 128
      model.n_layers: 3
      model.embedding_dim: 768
      model.encoder_type: "resnet"
