model:
  embedding_dim: 768
  hidden_dim: 256
  factor: 4
  n_layers: 3
  dropout: 0.1
  encoder_type: "resnet"

training:
  learning_rate: 0.001

data:
  batch_size: 32
  
logging:
  save_dir: "data/results/baseline/KIBA/cold"

gridsearch: # 2000s (40 mins) for a run, max 6 gb mem used on Davis -> 8 jobs, 48 hours each
  model.embedding_dim: [512, 768, 1024]
  model.encoder_type: ["resnet", "transformer"]
  model.hidden_dim: [128, 256, 512]
  model.n_layers: [1, 2, 3]

  training.learning_rate: [0.0005, 0.001, 0.002]
  data.batch_size: [16, 32, 64]

ensemble:
  configs:
    - training.learning_rate: 0.0005
      data.batch_size: 32
      model.hidden_dim: 128
      model.n_layers: 3
      model.embedding_dim: 768
      model.encoder_type: "resnet"
    
    - training.learning_rate: 0.0010
      data.batch_size: 16
      model.hidden_dim: 128
      model.n_layers: 2
      model.embedding_dim: 512
      model.encoder_type: "resnet"
    
    - training.learning_rate: 0.0020
      data.batch_size: 16
      model.hidden_dim: 128
      model.n_layers: 3
      model.embedding_dim: 512
      model.encoder_type: "resnet"
    
    - training.learning_rate: 0.0005
      data.batch_size: 16
      model.hidden_dim: 128
      model.n_layers: 2
      model.embedding_dim: 512
      model.encoder_type: "resnet"
    
    - training.learning_rate: 0.0010
      data.batch_size: 32
      model.hidden_dim: 128
      model.n_layers: 3
      model.embedding_dim: 768
      model.encoder_type: "resnet"
