# Multi-Hybrid Model Common Configuration
#   Combines multi-modal inputs with multi-output predictions
#   Supports individual branch pretraining with contrastive learning
#   These configurations are shared across all training phases

model:
  encoder_kwargs:
    dropout: 0.1
    activation: "gelu"
  aggregator_kwargs:
    dropout: 0.1
    activation: "gelu"
  inter_branch_aggregator_kwargs:
    dropout: 0.1
    activation: "gelu"
  dti_head_kwargs:
    dropout: 0.1
  
  # Contrastive learning parameters
  infonce_head_kwargs:
    output_dim: 128
    temperature: 0.07
  contrastive_weight: 1.0
  temperature: 0.07
    
training:
  scheduler: "one_cycle"  # "const", "step", "one_cycle", or "cosine"
    
data:
  h5_path: "dti.h5torch"
  drug_features: ["EMB-BiomedGraph", "EMB-BiomedImg", "EMB-BiomedText"]
  target_features: ["EMB-ESM", "EMB-NT"] 