model:
  drug_checkpoint_path: "data/results/multi_hybrid/pretrain/drug/multi_hybrid_pretrain_drug/checkpoints/best_model.pt"
  target_checkpoint_path: "data/results/multi_hybrid/pretrain/target/multi_hybrid_pretrain_target/checkpoints/best_model.pt"

training:
  learning_rate: 0.001
  
data:
  batch_size: 32

logging:
  experiment_name: "multi_hybrid_pretrain_rand"
  save_dir: "data/results/multi_hybrid/pretrain/rand"

gridsearch:
  # model.fusion_kwargs.hidden_dim: [128, 256, 512]
  # model.fusion_kwargs.n_layers: [1, 2, 3]
  training.learning_rate: [0.001, 0.0005, 0.0001]
  data.batch_size: [16, 32] 