# Multi-Modal Model Common Configuration
#   These configurations are not tuned 
#   They are shared across DAVIS/KIBA 
#   & cold_split/random_split experiments

model:
  encoder_kwargs:
    dropout: 0.1
    activation: "gelu"
  
  dti_head_kwargs:
    hidden_dim: 128
    
training:
  scheduler: "one_cycle"  # "const", "step", "one_cycle", or "cosine"
    
data:
  h5_path: "dti.h5torch"
  drug_feature: "FP-Morgan"
  target_feature: "FP-ESP"