model:
  checkpoint_path: "data/results/multi_output/pretrain/rand/multi_output_pretrain_rand/checkpoints/best_model.pt"

training:
  learning_rate: 0.0001

data:
  batch_size: 32
  
logging:
  experiment_name: "multi_output_DAVIS_rand"
  save_dir: "data/results/multi_output/DAVIS/rand"

gridsearch:
  training.learning_rate: [0.0001, 0.0005, 0.001]
  data.batch_size: [16, 32, 64]