training:
  learning_rate: 0.001
  
data:
  batch_size: 32

logging:
  experiment_name: "multi_output_pretrain_rand"
  save_dir: "data/results/multi_output/pretrain/rand"

gridsearch:
  model.fusion_kwargs.hidden_dim: [128, 256, 512]
  model.fusion_kwargs.n_layers: [1, 2, 3]
  training.learning_rate: [0.001, 0.0005, 0.0001]
  data.batch_size: [16, 32] 