model:
  embedding_dim: 768
  encoder_type: "transformer"
  encoder_kwargs:
    hidden_dim: 512
    n_layers: 2
  
  aggregator_type: "attentive"
  
  fusion_kwargs:
    hidden_dim: 512
    n_layers: 2
  
  # checkpoint_path: null  # Path to pretrained weights (set manually)

training:
  learning_rate: 0.0001

data:
  batch_size: 32
  
logging:
  experiment_name: "multi_hybrid_DAVIS_cold"
  save_dir: "data/results/multi_hybrid/DAVIS/cold"

gridsearch: # no changes to architecture (9 combinations only)
  training.learning_rate: [0.0001, 0.0005, 0.001]
  data.batch_size: [16, 32, 64]