training:
  learning_rate: 0.001
  
data:
  batch_size: 128                        # large bs for contrastive learning
  h5_path: "data/input/targets.h5torch"  # Use drug pretraining dataset
  drug_features: null
  target_features: ["EMB-ESM", "EMB-NT"]

logging:
  experiment_name: "full_pretrain_target"
  save_dir: "data/results/full/pretrain/target"