model:
  encoder_kwargs:
    hidden_dim: 512
    n_layers: 2
  
  aggregator_type: "attentive"
  
  fusion_kwargs:
    hidden_dim: 512
    n_layers: 2
  
  # Phase-specific parameters
  # checkpoint_path: null  # Path to pretrained weights (set manually)
  
  # Alternative: Load drug and target branches separately
  # drug_checkpoint_path: "outputs/full/pretrain/drug/best_model.pt"
  # target_checkpoint_path: "outputs/full/pretrain/target/best_model.pt"

training:
  learning_rate: 0.001
  
data:
  batch_size: 32

logging:
  experiment_name: "full_pretrain_cold"
  save_dir: "data/results/full/pretrain/cold"

gridsearch: # 162 combinations
  model.fusion_kwargs.hidden_dim: [128, 256, 512]
  model.fusion_kwargs.n_layers: [1, 2, 3]
  
  training.learning_rate: [0.001, 0.0005, 0.0001]
  data.batch_size: [16, 32] 