# Target branch pretraining configuration for Full DTI model
# Uses only contrastive loss (no VAE or reconstruction)

model:
  phase: pretrain_target

# Data configuration
data:
  h5_path: /home/robsyc/Desktop/thesis/MB-VAE-DTI/data/input/targets.h5torch
  drug_features: null
  target_features: ['EMB-ESM', 'EMB-NT']
  batch_size: 64
  num_workers: 4
  pin_memory: true
  shuffle_train: true
  drop_last: true
  load_in_memory: false

# Training configuration
training:
  max_epochs: 50
  learning_rate: 5e-4
  weight_decay: 1e-5
  early_stopping_patience: 15
  scheduler: cosine
  
# Logging configuration
logging:
  experiment_name: full_pretrain_target

# Gridsearch parameters
gridsearch:
  training.learning_rate: [1e-3, 5e-4, 1e-4]
  model.encoder_kwargs.dropout: [0.1, 0.2]
  model.temperature: [0.05, 0.07, 0.1] 